/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.1 */
/* Tue May  8 11:42:43 2012 */

/* parameterized module instance */
add_sub_16bit __ (.DataA( ), .DataB( ), .Add_Sub( ), .Result( ));
