/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.1 */
/* Thu Jun  7 09:49:40 2012 */

/* parameterized module instance */
add_sub_32_no_outreg __ (.DataA( ), .DataB( ), .Add_Sub( ), .Result( ), 
    .Overflow( ));
