/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.1 */
/* Tue May  8 12:58:28 2012 */

/* parameterized module instance */
add_sub_24bit __ (.DataA( ), .DataB( ), .Add_Sub( ), .Clock( ), 
    .Reset( ), .ClockEn( ), .Result( ), .Overflow( ));
