/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.1 */
/* Tue May  8 14:17:33 2012 */

/* parameterized module instance */
add_sub_24bit_no_outreg __ (.DataA( ), .DataB( ), .Add_Sub( ), 
    .Result( ), .Overflow( ));
