/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 1.2 */
/* /usr/local/diamond/1.2/ispfpga/bin/lin/scuba -w -n lattice_sin_cos_table -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type cosine -addr_width 10 -width 24 -pfu -input_reg -mode 4 -output_reg -area -pipeline 1 -e  */
/* Fri Jun  1 13:42:36 2012 */


`timescale 1 ns / 1 ps
module lattice_sin_cos_table (Clock, ClkEn, Reset, Theta, Sine);
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [9:0] Theta;
    output wire [23:0] Sine;

    wire func_or_inet_1;
    wire func_or_inet;
    wire lx_ne0;
    wire lx_ne0_inv;
    wire mx_ctrl_r_inv;
    wire rom_addr0_r;
    wire rom_addr0_r_1;
    wire rom_addr0_r_2;
    wire rom_addr0_r_3;
    wire rom_addr0_r_4;
    wire rom_addr0_r_5;
    wire rom_addr0_r_6;
    wire mx_ctrl_r;
    wire rom_addr0_r_7;
    wire mx_ctrl_r_1;
    wire rom_dout;
    wire rom_dout_1;
    wire rom_dout_2;
    wire rom_dout_3;
    wire rom_dout_4;
    wire rom_dout_5;
    wire rom_dout_6;
    wire rom_dout_7;
    wire rom_dout_8;
    wire rom_dout_9;
    wire rom_dout_10;
    wire rom_dout_11;
    wire rom_dout_12;
    wire rom_dout_13;
    wire rom_dout_14;
    wire rom_dout_15;
    wire rom_dout_16;
    wire rom_dout_17;
    wire rom_dout_18;
    wire rom_dout_19;
    wire rom_dout_20;
    wire rom_dout_21;
    wire rom_dout_22;
    wire sinromoutsel;
    wire rom_dout_23;
    wire out_sel_i;
    wire rom_dout_24;
    wire rom_dout_25;
    wire rom_dout_26;
    wire rom_dout_27;
    wire rom_dout_28;
    wire rom_dout_29;
    wire rom_dout_30;
    wire rom_dout_31;
    wire rom_dout_32;
    wire rom_dout_33;
    wire rom_dout_34;
    wire rom_dout_35;
    wire rom_dout_36;
    wire rom_dout_37;
    wire rom_dout_38;
    wire rom_dout_39;
    wire rom_dout_40;
    wire rom_dout_41;
    wire rom_dout_42;
    wire rom_dout_43;
    wire rom_dout_44;
    wire rom_dout_45;
    wire rom_dout_46;
    wire out_sel;
    wire rom_dout_47;
    wire sinout_pre;
    wire sinout_pre_1;
    wire sinout_pre_2;
    wire sinout_pre_3;
    wire sinout_pre_4;
    wire sinout_pre_5;
    wire sinout_pre_6;
    wire sinout_pre_7;
    wire sinout_pre_8;
    wire sinout_pre_9;
    wire sinout_pre_10;
    wire sinout_pre_11;
    wire sinout_pre_12;
    wire sinout_pre_13;
    wire sinout_pre_14;
    wire sinout_pre_15;
    wire sinout_pre_16;
    wire sinout_pre_17;
    wire sinout_pre_18;
    wire sinout_pre_19;
    wire sinout_pre_20;
    wire sinout_pre_21;
    wire sinout_pre_22;
    wire sinout_pre_23;
    wire rom_addr0_r_n;
    wire rom_addr0_r_n_1;
    wire rom_addr0_r_inv;
    wire rom_addr0_r_1_inv;
    wire rom_addr0_r_n_2;
    wire rom_addr0_r_n_3;
    wire co0;
    wire rom_addr0_r_2_inv;
    wire rom_addr0_r_3_inv;
    wire rom_addr0_r_n_4;
    wire rom_addr0_r_n_5;
    wire co1;
    wire rom_addr0_r_4_inv;
    wire rom_addr0_r_5_inv;
    wire rom_addr0_r_n_6;
    wire rom_addr0_r_n_7;
    wire co2;
    wire rom_addr0_r_6_inv;
    wire rom_addr0_r_7_inv;
    wire co3d;
    wire co3;
    wire rom_dout_23_ffin;
    wire rom_dout_22_ffin;
    wire rom_dout_21_ffin;
    wire rom_dout_20_ffin;
    wire rom_dout_19_ffin;
    wire rom_dout_18_ffin;
    wire rom_dout_17_ffin;
    wire rom_dout_16_ffin;
    wire rom_dout_15_ffin;
    wire rom_dout_14_ffin;
    wire rom_dout_13_ffin;
    wire rom_dout_12_ffin;
    wire rom_dout_11_ffin;
    wire rom_dout_10_ffin;
    wire rom_dout_9_ffin;
    wire rom_dout_8_ffin;
    wire rom_dout_7_ffin;
    wire rom_dout_6_ffin;
    wire rom_dout_5_ffin;
    wire rom_dout_4_ffin;
    wire rom_dout_3_ffin;
    wire rom_dout_2_ffin;
    wire rom_dout_1_ffin;
    wire rom_dout_ffin;
    wire rom_addr0_r_n_8;
    wire rom_addr0_r_n_9;
    wire rom_addr0_r_n_10;
    wire rom_addr0_r_n_11;
    wire rom_addr0_r_n_12;
    wire rom_addr0_r_n_13;
    wire rom_addr0_r_n_14;
    wire rom_addr0_r_n_15;
    wire rom_dout_n;
    wire rom_dout_n_1;
    wire scuba_vhi;
    wire rom_dout_inv;
    wire rom_dout_1_inv;
    wire rom_dout_n_2;
    wire rom_dout_n_3;
    wire co0_1;
    wire rom_dout_2_inv;
    wire rom_dout_3_inv;
    wire rom_dout_n_4;
    wire rom_dout_n_5;
    wire co1_1;
    wire rom_dout_4_inv;
    wire rom_dout_5_inv;
    wire rom_dout_n_6;
    wire rom_dout_n_7;
    wire co2_1;
    wire rom_dout_6_inv;
    wire rom_dout_7_inv;
    wire rom_dout_n_8;
    wire rom_dout_n_9;
    wire co3_1;
    wire rom_dout_8_inv;
    wire rom_dout_9_inv;
    wire rom_dout_n_10;
    wire rom_dout_n_11;
    wire co4;
    wire rom_dout_10_inv;
    wire rom_dout_11_inv;
    wire rom_dout_n_12;
    wire rom_dout_n_13;
    wire co5;
    wire rom_dout_12_inv;
    wire rom_dout_13_inv;
    wire rom_dout_n_14;
    wire rom_dout_n_15;
    wire co6;
    wire rom_dout_14_inv;
    wire rom_dout_15_inv;
    wire rom_dout_n_16;
    wire rom_dout_n_17;
    wire co7;
    wire rom_dout_16_inv;
    wire rom_dout_17_inv;
    wire rom_dout_n_18;
    wire rom_dout_n_19;
    wire co8;
    wire rom_dout_18_inv;
    wire rom_dout_19_inv;
    wire rom_dout_n_20;
    wire rom_dout_n_21;
    wire co9;
    wire rom_dout_20_inv;
    wire rom_dout_21_inv;
    wire rom_dout_n_22;
    wire rom_dout_n_23;
    wire co10;
    wire rom_dout_22_inv;
    wire rom_dout_23_inv;
    wire co11d;
    wire co11;
    wire scuba_vlo;

    INV INV_33 (.A(rom_addr0_r_7), .Z(rom_addr0_r_7_inv));

    INV INV_32 (.A(rom_addr0_r_6), .Z(rom_addr0_r_6_inv));

    INV INV_31 (.A(rom_addr0_r_5), .Z(rom_addr0_r_5_inv));

    INV INV_30 (.A(rom_addr0_r_4), .Z(rom_addr0_r_4_inv));

    INV INV_29 (.A(rom_addr0_r_3), .Z(rom_addr0_r_3_inv));

    INV INV_28 (.A(rom_addr0_r_2), .Z(rom_addr0_r_2_inv));

    INV INV_27 (.A(rom_addr0_r_1), .Z(rom_addr0_r_1_inv));

    INV INV_26 (.A(rom_addr0_r), .Z(rom_addr0_r_inv));

    INV INV_25 (.A(rom_dout_23), .Z(rom_dout_23_inv));

    INV INV_24 (.A(rom_dout_22), .Z(rom_dout_22_inv));

    INV INV_23 (.A(rom_dout_21), .Z(rom_dout_21_inv));

    INV INV_22 (.A(rom_dout_20), .Z(rom_dout_20_inv));

    INV INV_21 (.A(rom_dout_19), .Z(rom_dout_19_inv));

    INV INV_20 (.A(rom_dout_18), .Z(rom_dout_18_inv));

    INV INV_19 (.A(rom_dout_17), .Z(rom_dout_17_inv));

    INV INV_18 (.A(rom_dout_16), .Z(rom_dout_16_inv));

    INV INV_17 (.A(rom_dout_15), .Z(rom_dout_15_inv));

    INV INV_16 (.A(rom_dout_14), .Z(rom_dout_14_inv));

    INV INV_15 (.A(rom_dout_13), .Z(rom_dout_13_inv));

    INV INV_14 (.A(rom_dout_12), .Z(rom_dout_12_inv));

    INV INV_13 (.A(rom_dout_11), .Z(rom_dout_11_inv));

    INV INV_12 (.A(rom_dout_10), .Z(rom_dout_10_inv));

    INV INV_11 (.A(rom_dout_9), .Z(rom_dout_9_inv));

    INV INV_10 (.A(rom_dout_8), .Z(rom_dout_8_inv));

    INV INV_9 (.A(rom_dout_7), .Z(rom_dout_7_inv));

    INV INV_8 (.A(rom_dout_6), .Z(rom_dout_6_inv));

    INV INV_7 (.A(rom_dout_5), .Z(rom_dout_5_inv));

    INV INV_6 (.A(rom_dout_4), .Z(rom_dout_4_inv));

    INV INV_5 (.A(rom_dout_3), .Z(rom_dout_3_inv));

    INV INV_4 (.A(rom_dout_2), .Z(rom_dout_2_inv));

    INV INV_3 (.A(rom_dout_1), .Z(rom_dout_1_inv));

    INV INV_2 (.A(rom_dout), .Z(rom_dout_inv));

    // synopsys translate_off
    defparam LUT4_2.initval =  16'hfffe ;
    // synopsys translate_on
    ROM16X1 LUT4_2 (.AD3(rom_addr0_r_n_8), .AD2(rom_addr0_r_n_9), .AD1(rom_addr0_r_n_10), 
        .AD0(rom_addr0_r_n_11), .DO0(func_or_inet))
             /* synthesis initval="0xfffe" */;

    // synopsys translate_off
    defparam LUT4_1.initval =  16'hfffe ;
    // synopsys translate_on
    ROM16X1 LUT4_1 (.AD3(rom_addr0_r_n_12), .AD2(rom_addr0_r_n_13), .AD1(rom_addr0_r_n_14), 
        .AD0(rom_addr0_r_n_15), .DO0(func_or_inet_1))
             /* synthesis initval="0xfffe" */;

    // synopsys translate_off
    defparam LUT4_0.initval =  16'hfffe ;
    // synopsys translate_on
    ROM16X1 LUT4_0 (.AD3(func_or_inet), .AD2(func_or_inet_1), .AD1(scuba_vlo), 
        .AD0(scuba_vlo), .DO0(lx_ne0))
             /* synthesis initval="0xfffe" */;

    INV INV_1 (.A(lx_ne0), .Z(lx_ne0_inv));

    INV INV_0 (.A(mx_ctrl_r), .Z(mx_ctrl_r_inv));

    AND2 AND2_t0 (.A(mx_ctrl_r_inv), .B(lx_ne0_inv), .Z(out_sel_i));

    // synopsys translate_off
    defparam FF_59.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_59 (.D(Theta[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_58.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_58 (.D(Theta[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_57.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_57 (.D(Theta[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_56.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_56 (.D(Theta[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_55.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_55 (.D(Theta[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_54.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_54 (.D(Theta[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_53.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_53 (.D(Theta[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_52.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_52 (.D(Theta[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_51.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_51 (.D(Theta[8]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_50.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_50 (.D(Theta[9]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r_1))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_55 (.D0(rom_addr0_r_n), .D1(rom_addr0_r), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_8));

    MUX21 muxb_54 (.D0(rom_addr0_r_n_1), .D1(rom_addr0_r_1), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_9));

    MUX21 muxb_53 (.D0(rom_addr0_r_n_2), .D1(rom_addr0_r_2), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_10));

    MUX21 muxb_52 (.D0(rom_addr0_r_n_3), .D1(rom_addr0_r_3), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_11));

    MUX21 muxb_51 (.D0(rom_addr0_r_n_4), .D1(rom_addr0_r_4), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_12));

    MUX21 muxb_50 (.D0(rom_addr0_r_n_5), .D1(rom_addr0_r_5), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_13));

    MUX21 muxb_49 (.D0(rom_addr0_r_n_6), .D1(rom_addr0_r_6), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_14));

    MUX21 muxb_48 (.D0(rom_addr0_r_n_7), .D1(rom_addr0_r_7), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_15));

    // synopsys translate_off
    defparam FF_49.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_49 (.D(rom_dout_23_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_23))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_48.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_48 (.D(rom_dout_22_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_22))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_47.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_47 (.D(rom_dout_21_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_21))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_46.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_46 (.D(rom_dout_20_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_20))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_45.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_45 (.D(rom_dout_19_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_19))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_44.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_44 (.D(rom_dout_18_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_18))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_43.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_43 (.D(rom_dout_17_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_17))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_42.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_42 (.D(rom_dout_16_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_16))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_41.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_41 (.D(rom_dout_15_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_15))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_40.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_40 (.D(rom_dout_14_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_14))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_39.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_39 (.D(rom_dout_13_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_13))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_38.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_38 (.D(rom_dout_12_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_12))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_37.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_37 (.D(rom_dout_11_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_11))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_36.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_36 (.D(rom_dout_10_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_10))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_35.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_35 (.D(rom_dout_9_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_9))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_34.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_34 (.D(rom_dout_8_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_8))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_33.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_33 (.D(rom_dout_7_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_7))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_32.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_32 (.D(rom_dout_6_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_6))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_31.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_31 (.D(rom_dout_5_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_5))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_30.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_30 (.D(rom_dout_4_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_4))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_29.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_29 (.D(rom_dout_3_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_3))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_28.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_28 (.D(rom_dout_2_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_2))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_27.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_27 (.D(rom_dout_1_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout_1))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_26.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_26 (.D(rom_dout_ffin), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(rom_dout))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_25.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_25 (.D(mx_ctrl_r_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(sinromoutsel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_47 (.D0(rom_dout), .D1(rom_dout_n), .SD(sinromoutsel), .Z(rom_dout_24));

    MUX21 muxb_46 (.D0(rom_dout_1), .D1(rom_dout_n_1), .SD(sinromoutsel), 
        .Z(rom_dout_25));

    MUX21 muxb_45 (.D0(rom_dout_2), .D1(rom_dout_n_2), .SD(sinromoutsel), 
        .Z(rom_dout_26));

    MUX21 muxb_44 (.D0(rom_dout_3), .D1(rom_dout_n_3), .SD(sinromoutsel), 
        .Z(rom_dout_27));

    MUX21 muxb_43 (.D0(rom_dout_4), .D1(rom_dout_n_4), .SD(sinromoutsel), 
        .Z(rom_dout_28));

    MUX21 muxb_42 (.D0(rom_dout_5), .D1(rom_dout_n_5), .SD(sinromoutsel), 
        .Z(rom_dout_29));

    MUX21 muxb_41 (.D0(rom_dout_6), .D1(rom_dout_n_6), .SD(sinromoutsel), 
        .Z(rom_dout_30));

    MUX21 muxb_40 (.D0(rom_dout_7), .D1(rom_dout_n_7), .SD(sinromoutsel), 
        .Z(rom_dout_31));

    MUX21 muxb_39 (.D0(rom_dout_8), .D1(rom_dout_n_8), .SD(sinromoutsel), 
        .Z(rom_dout_32));

    MUX21 muxb_38 (.D0(rom_dout_9), .D1(rom_dout_n_9), .SD(sinromoutsel), 
        .Z(rom_dout_33));

    MUX21 muxb_37 (.D0(rom_dout_10), .D1(rom_dout_n_10), .SD(sinromoutsel), 
        .Z(rom_dout_34));

    MUX21 muxb_36 (.D0(rom_dout_11), .D1(rom_dout_n_11), .SD(sinromoutsel), 
        .Z(rom_dout_35));

    MUX21 muxb_35 (.D0(rom_dout_12), .D1(rom_dout_n_12), .SD(sinromoutsel), 
        .Z(rom_dout_36));

    MUX21 muxb_34 (.D0(rom_dout_13), .D1(rom_dout_n_13), .SD(sinromoutsel), 
        .Z(rom_dout_37));

    MUX21 muxb_33 (.D0(rom_dout_14), .D1(rom_dout_n_14), .SD(sinromoutsel), 
        .Z(rom_dout_38));

    MUX21 muxb_32 (.D0(rom_dout_15), .D1(rom_dout_n_15), .SD(sinromoutsel), 
        .Z(rom_dout_39));

    MUX21 muxb_31 (.D0(rom_dout_16), .D1(rom_dout_n_16), .SD(sinromoutsel), 
        .Z(rom_dout_40));

    MUX21 muxb_30 (.D0(rom_dout_17), .D1(rom_dout_n_17), .SD(sinromoutsel), 
        .Z(rom_dout_41));

    MUX21 muxb_29 (.D0(rom_dout_18), .D1(rom_dout_n_18), .SD(sinromoutsel), 
        .Z(rom_dout_42));

    MUX21 muxb_28 (.D0(rom_dout_19), .D1(rom_dout_n_19), .SD(sinromoutsel), 
        .Z(rom_dout_43));

    MUX21 muxb_27 (.D0(rom_dout_20), .D1(rom_dout_n_20), .SD(sinromoutsel), 
        .Z(rom_dout_44));

    MUX21 muxb_26 (.D0(rom_dout_21), .D1(rom_dout_n_21), .SD(sinromoutsel), 
        .Z(rom_dout_45));

    MUX21 muxb_25 (.D0(rom_dout_22), .D1(rom_dout_n_22), .SD(sinromoutsel), 
        .Z(rom_dout_46));

    MUX21 muxb_24 (.D0(rom_dout_23), .D1(rom_dout_n_23), .SD(sinromoutsel), 
        .Z(rom_dout_47));

    // synopsys translate_off
    defparam FF_24.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_24 (.D(out_sel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(out_sel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_23 (.D0(rom_dout_24), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre));

    MUX21 muxb_22 (.D0(rom_dout_25), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_1));

    MUX21 muxb_21 (.D0(rom_dout_26), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_2));

    MUX21 muxb_20 (.D0(rom_dout_27), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_3));

    MUX21 muxb_19 (.D0(rom_dout_28), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_4));

    MUX21 muxb_18 (.D0(rom_dout_29), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_5));

    MUX21 muxb_17 (.D0(rom_dout_30), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_6));

    MUX21 muxb_16 (.D0(rom_dout_31), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_7));

    MUX21 muxb_15 (.D0(rom_dout_32), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_8));

    MUX21 muxb_14 (.D0(rom_dout_33), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_9));

    MUX21 muxb_13 (.D0(rom_dout_34), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_10));

    MUX21 muxb_12 (.D0(rom_dout_35), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_11));

    MUX21 muxb_11 (.D0(rom_dout_36), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_12));

    MUX21 muxb_10 (.D0(rom_dout_37), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_13));

    MUX21 muxb_9 (.D0(rom_dout_38), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_14));

    MUX21 muxb_8 (.D0(rom_dout_39), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_15));

    MUX21 muxb_7 (.D0(rom_dout_40), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_16));

    MUX21 muxb_6 (.D0(rom_dout_41), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_17));

    MUX21 muxb_5 (.D0(rom_dout_42), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_18));

    MUX21 muxb_4 (.D0(rom_dout_43), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_19));

    MUX21 muxb_3 (.D0(rom_dout_44), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_20));

    MUX21 muxb_2 (.D0(rom_dout_45), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_21));

    MUX21 muxb_1 (.D0(rom_dout_46), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_22));

    MUX21 muxb_0 (.D0(rom_dout_47), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_23));

    // synopsys translate_off
    defparam FF_23.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_23 (.D(sinout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_22.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_22 (.D(sinout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_21 (.D(sinout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(sinout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(sinout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(sinout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(sinout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(sinout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(sinout_pre_8), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(sinout_pre_9), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(sinout_pre_10), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(sinout_pre_11), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(sinout_pre_12), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(sinout_pre_13), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_9 (.D(sinout_pre_14), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_8 (.D(sinout_pre_15), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_7 (.D(sinout_pre_16), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(sinout_pre_17), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(sinout_pre_18), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[18]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(sinout_pre_19), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[19]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(sinout_pre_20), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[20]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(sinout_pre_21), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[21]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(sinout_pre_22), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[22]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(sinout_pre_23), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[23]))
             /* synthesis GSR="ENABLED" */;

    FADD2B neg_rom_addr0_r_n_0 (.A0(rom_addr0_r_inv), .A1(rom_addr0_r_1_inv), 
        .B0(scuba_vhi), .B1(scuba_vlo), .CI(scuba_vlo), .COUT(co0), .S0(rom_addr0_r_n), 
        .S1(rom_addr0_r_n_1));

    FADD2B neg_rom_addr0_r_n_1 (.A0(rom_addr0_r_2_inv), .A1(rom_addr0_r_3_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co0), .COUT(co1), .S0(rom_addr0_r_n_2), 
        .S1(rom_addr0_r_n_3));

    FADD2B neg_rom_addr0_r_n_2 (.A0(rom_addr0_r_4_inv), .A1(rom_addr0_r_5_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co1), .COUT(co2), .S0(rom_addr0_r_n_4), 
        .S1(rom_addr0_r_n_5));

    FADD2B neg_rom_addr0_r_n_3 (.A0(rom_addr0_r_6_inv), .A1(rom_addr0_r_7_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co2), .COUT(co3), .S0(rom_addr0_r_n_6), 
        .S1(rom_addr0_r_n_7));

    FADD2B neg_rom_addr0_r_nd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co3), .COUT(), .S0(co3d), .S1());

    // synopsys translate_off
    defparam triglut_1_0_23.initval = 256'h0000000000000000000000000000000000000000000000000000000000000000 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_23 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_23_ffin))
             /* synthesis initval="0x0000000000000000000000000000000000000000000000000000000000000000" */;

    // synopsys translate_off
    defparam triglut_1_0_22.initval = 256'h0000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_22 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_22_ffin))
             /* synthesis initval="0x0000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_21.initval = 256'h00000000007FFFFFFFFFF80000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_21 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_21_ffin))
             /* synthesis initval="0x00000000007FFFFFFFFFF80000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_20.initval = 256'h00000FFFFF800003FFFFF8000003FFFFFFC000000007FFFFFFFFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_20 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_20_ffin))
             /* synthesis initval="0x00000FFFFF800003FFFFF8000003FFFFFFC000000007FFFFFFFFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_19.initval = 256'h003FF003FF801FFC007FF8007FFC001FFFC0003FFFF8000003FFFFFFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_19 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_19_ffin))
             /* synthesis initval="0x003FF003FF801FFC007FF8007FFC001FFFC0003FFFF8000003FFFFFFFFFFFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_18.initval = 256'h07C1F07C1F83E07C0F81F81F81FC0FE03FC03FC01FF800FFFC0001FFFFFFFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_18 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_18_ffin))
             /* synthesis initval="0x07C1F07C1F83E07C0F81F81F81FC0FE03FC03FC01FF800FFFC0001FFFFFFFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_17.initval = 256'h39CE738C639C639C738E38E38E3C70E1C3C3C3C1E0F81F01FC07FE001FFFFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_17 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_17_ffin))
             /* synthesis initval="0x39CE738C639C639C738E38E38E3C70E1C3C3C3C1E0F81F01FC07FE001FFFFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_16.initval = 256'h5AD294B4A5A5A5A4B492DB6DB24DB366CCCCCCCE6318E71E3C783E0FE01FFFFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_16 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_16_ffin))
             /* synthesis initval="0x5AD294B4A5A5A5A4B492DB6DB24DB366CCCCCCCE6318E71E3C783E0FE01FFFFF" */;

    // synopsys translate_off
    defparam triglut_1_0_15.initval = 256'hCC673199CCCCCCCD9936492496D695AB55555556AD6B6926CD98CE71E1E07FFF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_15 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_15_ffin))
             /* synthesis initval="0xCC673199CCCCCCCD9936492496D695AB55555556AD6B6926CD98CE71E1E07FFF" */;

    // synopsys translate_off
    defparam triglut_1_0_14.initval = 256'hAB56A9552AAAAAAB54AD2DB6CC8CC71E07FFFF83C739B24B56AB5692666387FF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_14 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_14_ffin))
             /* synthesis initval="0xAB56A9552AAAAAAB54AD2DB6CC8CC71E07FFFF83C739B24B56AB5692666387FF" */;

    // synopsys translate_off
    defparam triglut_1_0_13.initval = 256'h1E3C3C1F803FFE01E1C666DA55B54B26387FF87336A529263C01E336AAAD98FF ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_13 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_13_ffin))
             /* synthesis initval="0x1E3C3C1F803FFE01E1C666DA55B54B26387FF87336A529263C01E336AAAD98FF" */;

    // synopsys translate_off
    defparam triglut_1_0_12.initval = 256'h66CCCC6387C001F1992554B31F1F196ADB87866AA4F0736A4C019AA4FFE4A93F ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_12 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_12_ffin))
             /* synthesis initval="0x66CCCC6387C001F1992554B31F1F196ADB87866AA4F0736A4C019AA4FFE4A93F" */;

    // synopsys translate_off
    defparam triglut_1_0_11.initval = 256'hAA5555AD99C1C1C955B061956F1CD4C068B8754FED306AC0D47953CD3F96034F ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_11 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_11_ffin))
             /* synthesis initval="0xAA5555AD99C1C1C955B061956F1CD4C068B8754FED306AC0D47953CD3F96034F" */;

    // synopsys translate_off
    defparam triglut_1_0_10.initval = 256'h1F0000C4AACE39ACFED3994F331A814C5D9867D798505F5E9985F4285F42FA17 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_10 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_10_ffin))
             /* synthesis initval="0x1F0000C4AACE39ACFED3994F331A814C5D9867D798505F5E9985F4285F42FA17" */;

    // synopsys translate_off
    defparam triglut_1_0_9.initval = 256'h673FF8B27E56350579859590A71FBC930DC94BB04B776EE0A4B2E8BB6E81761B ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_9 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_9_ffin))
             /* synthesis initval="0x673FF8B27E56350579859590A71FBC930DC94BB04B776EE0A4B2E8BB6E81761B" */;

    // synopsys translate_off
    defparam triglut_1_0_8.initval = 256'hAB4FF666BD7A2F3784829E46E5F75942654ECF4B0C3E9FCD60C5557C1F5AF8C7 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_8 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_8_ffin))
             /* synthesis initval="0xAB4FF666BD7A2F3784829E46E5F75942654ECF4B0C3E9FCD60C5557C1F5AF8C7" */;

    // synopsys translate_off
    defparam triglut_1_0_7.initval = 256'h0193ECA5DBB436433CF58C71C113A17204421D99C0C9057D05CCA716B45A21E5 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_7 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_7_ffin))
             /* synthesis initval="0x0193ECA5DBB436433CF58C71C113A17204421D99C0C9057D05CCA716B45A21E5" */;

    // synopsys translate_off
    defparam triglut_1_0_6.initval = 256'h0145C4E687CA8CCFF0349EDBE557827709222CAAC0A307B07024E559CD66ACCB ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_6 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_6_ffin))
             /* synthesis initval="0x0145C4E687CA8CCFF0349EDBE557827709222CAAC0A307B07024E559CD66ACCB" */;

    // synopsys translate_off
    defparam triglut_1_0_5.initval = 256'h38861C6361725B68312D4C07455611C59172460E5EC2730B06F445A0C6C3581B ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_5 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_5_ffin))
             /* synthesis initval="0x38861C6361725B68312D4C07455611C59172460E5EC2730B06F445A0C6C3581B" */;

    // synopsys translate_off
    defparam triglut_1_0_4.initval = 256'hC55187DD25E23B6456F3472C3802C0B3CD5AE6716C2E20D82E2A0181BBBD1429 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_4 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_4_ffin))
             /* synthesis initval="0xC55187DD25E23B6456F3472C3802C0B3CD5AE6716C2E20D82E2A0181BBBD1429" */;

    // synopsys translate_off
    defparam triglut_1_0_3.initval = 256'h554E80858B8530F882BF3B332C1B145B25B236B19363F16BFCECABD3AAA4E345 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_3 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_3_ffin))
             /* synthesis initval="0x554E80858B8530F882BF3B332C1B145B25B236B19363F16BFCECABD3AAA4E345" */;

    // synopsys translate_off
    defparam triglut_1_0_2.initval = 256'h6842B2D288B3A5C340FE091D5E27A1DE85E886140D295FCFB1BD99F1D543FEE1 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_2 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_2_ffin))
             /* synthesis initval="0x6842B2D288B3A5C340FE091D5E27A1DE85E886140D295FCFB1BD99F1D543FEE1" */;

    // synopsys translate_off
    defparam triglut_1_0_1.initval = 256'h3881724E320AE0B6BAAFF5ACC0605C6BA883601860F00A55F60C643BC1D9B49B ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_1 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_1_ffin))
             /* synthesis initval="0x3881724E320AE0B6BAAFF5ACC0605C6BA883601860F00A55F60C643BC1D9B49B" */;

    // synopsys translate_off
    defparam triglut_1_0_0.initval = 256'h7DA9764A29121F2372346A791C5D33DC7720D31BBDB67039B24F64B766013089 ;
    // synopsys translate_on
    ROM256X1 triglut_1_0_0 (.AD7(rom_addr0_r_n_15), .AD6(rom_addr0_r_n_14), 
        .AD5(rom_addr0_r_n_13), .AD4(rom_addr0_r_n_12), .AD3(rom_addr0_r_n_11), 
        .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_9), .AD0(rom_addr0_r_n_8), 
        .DO0(rom_dout_ffin))
             /* synthesis initval="0x7DA9764A29121F2372346A791C5D33DC7720D31BBDB67039B24F64B766013089" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B neg_rom_dout_n_0 (.A0(rom_dout_inv), .A1(rom_dout_1_inv), .B0(scuba_vhi), 
        .B1(scuba_vlo), .CI(scuba_vlo), .COUT(co0_1), .S0(rom_dout_n), .S1(rom_dout_n_1));

    FADD2B neg_rom_dout_n_1 (.A0(rom_dout_2_inv), .A1(rom_dout_3_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co0_1), .COUT(co1_1), .S0(rom_dout_n_2), .S1(rom_dout_n_3));

    FADD2B neg_rom_dout_n_2 (.A0(rom_dout_4_inv), .A1(rom_dout_5_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co1_1), .COUT(co2_1), .S0(rom_dout_n_4), .S1(rom_dout_n_5));

    FADD2B neg_rom_dout_n_3 (.A0(rom_dout_6_inv), .A1(rom_dout_7_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co2_1), .COUT(co3_1), .S0(rom_dout_n_6), .S1(rom_dout_n_7));

    FADD2B neg_rom_dout_n_4 (.A0(rom_dout_8_inv), .A1(rom_dout_9_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co3_1), .COUT(co4), .S0(rom_dout_n_8), .S1(rom_dout_n_9));

    FADD2B neg_rom_dout_n_5 (.A0(rom_dout_10_inv), .A1(rom_dout_11_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co4), .COUT(co5), .S0(rom_dout_n_10), 
        .S1(rom_dout_n_11));

    FADD2B neg_rom_dout_n_6 (.A0(rom_dout_12_inv), .A1(rom_dout_13_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co5), .COUT(co6), .S0(rom_dout_n_12), 
        .S1(rom_dout_n_13));

    FADD2B neg_rom_dout_n_7 (.A0(rom_dout_14_inv), .A1(rom_dout_15_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co6), .COUT(co7), .S0(rom_dout_n_14), 
        .S1(rom_dout_n_15));

    FADD2B neg_rom_dout_n_8 (.A0(rom_dout_16_inv), .A1(rom_dout_17_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co7), .COUT(co8), .S0(rom_dout_n_16), 
        .S1(rom_dout_n_17));

    FADD2B neg_rom_dout_n_9 (.A0(rom_dout_18_inv), .A1(rom_dout_19_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co8), .COUT(co9), .S0(rom_dout_n_18), 
        .S1(rom_dout_n_19));

    FADD2B neg_rom_dout_n_10 (.A0(rom_dout_20_inv), .A1(rom_dout_21_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co9), .COUT(co10), .S0(rom_dout_n_20), 
        .S1(rom_dout_n_21));

    FADD2B neg_rom_dout_n_11 (.A0(rom_dout_22_inv), .A1(rom_dout_23_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co10), .COUT(co11), .S0(rom_dout_n_22), 
        .S1(rom_dout_n_23));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B neg_rom_dout_nd (.A0(scuba_vlo), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co11), .COUT(), .S0(co11d), .S1());



    // exemplar begin
    // exemplar attribute LUT4_2 initval 0xfffe
    // exemplar attribute LUT4_1 initval 0xfffe
    // exemplar attribute LUT4_0 initval 0xfffe
    // exemplar attribute FF_59 GSR ENABLED
    // exemplar attribute FF_58 GSR ENABLED
    // exemplar attribute FF_57 GSR ENABLED
    // exemplar attribute FF_56 GSR ENABLED
    // exemplar attribute FF_55 GSR ENABLED
    // exemplar attribute FF_54 GSR ENABLED
    // exemplar attribute FF_53 GSR ENABLED
    // exemplar attribute FF_52 GSR ENABLED
    // exemplar attribute FF_51 GSR ENABLED
    // exemplar attribute FF_50 GSR ENABLED
    // exemplar attribute FF_49 GSR ENABLED
    // exemplar attribute FF_48 GSR ENABLED
    // exemplar attribute FF_47 GSR ENABLED
    // exemplar attribute FF_46 GSR ENABLED
    // exemplar attribute FF_45 GSR ENABLED
    // exemplar attribute FF_44 GSR ENABLED
    // exemplar attribute FF_43 GSR ENABLED
    // exemplar attribute FF_42 GSR ENABLED
    // exemplar attribute FF_41 GSR ENABLED
    // exemplar attribute FF_40 GSR ENABLED
    // exemplar attribute FF_39 GSR ENABLED
    // exemplar attribute FF_38 GSR ENABLED
    // exemplar attribute FF_37 GSR ENABLED
    // exemplar attribute FF_36 GSR ENABLED
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute triglut_1_0_23 initval 0x0000000000000000000000000000000000000000000000000000000000000000
    // exemplar attribute triglut_1_0_22 initval 0x0000000000000000000007FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    // exemplar attribute triglut_1_0_21 initval 0x00000000007FFFFFFFFFF80000000000003FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    // exemplar attribute triglut_1_0_20 initval 0x00000FFFFF800003FFFFF8000003FFFFFFC000000007FFFFFFFFFFFFFFFFFFFF
    // exemplar attribute triglut_1_0_19 initval 0x003FF003FF801FFC007FF8007FFC001FFFC0003FFFF8000003FFFFFFFFFFFFFF
    // exemplar attribute triglut_1_0_18 initval 0x07C1F07C1F83E07C0F81F81F81FC0FE03FC03FC01FF800FFFC0001FFFFFFFFFF
    // exemplar attribute triglut_1_0_17 initval 0x39CE738C639C639C738E38E38E3C70E1C3C3C3C1E0F81F01FC07FE001FFFFFFF
    // exemplar attribute triglut_1_0_16 initval 0x5AD294B4A5A5A5A4B492DB6DB24DB366CCCCCCCE6318E71E3C783E0FE01FFFFF
    // exemplar attribute triglut_1_0_15 initval 0xCC673199CCCCCCCD9936492496D695AB55555556AD6B6926CD98CE71E1E07FFF
    // exemplar attribute triglut_1_0_14 initval 0xAB56A9552AAAAAAB54AD2DB6CC8CC71E07FFFF83C739B24B56AB5692666387FF
    // exemplar attribute triglut_1_0_13 initval 0x1E3C3C1F803FFE01E1C666DA55B54B26387FF87336A529263C01E336AAAD98FF
    // exemplar attribute triglut_1_0_12 initval 0x66CCCC6387C001F1992554B31F1F196ADB87866AA4F0736A4C019AA4FFE4A93F
    // exemplar attribute triglut_1_0_11 initval 0xAA5555AD99C1C1C955B061956F1CD4C068B8754FED306AC0D47953CD3F96034F
    // exemplar attribute triglut_1_0_10 initval 0x1F0000C4AACE39ACFED3994F331A814C5D9867D798505F5E9985F4285F42FA17
    // exemplar attribute triglut_1_0_9 initval 0x673FF8B27E56350579859590A71FBC930DC94BB04B776EE0A4B2E8BB6E81761B
    // exemplar attribute triglut_1_0_8 initval 0xAB4FF666BD7A2F3784829E46E5F75942654ECF4B0C3E9FCD60C5557C1F5AF8C7
    // exemplar attribute triglut_1_0_7 initval 0x0193ECA5DBB436433CF58C71C113A17204421D99C0C9057D05CCA716B45A21E5
    // exemplar attribute triglut_1_0_6 initval 0x0145C4E687CA8CCFF0349EDBE557827709222CAAC0A307B07024E559CD66ACCB
    // exemplar attribute triglut_1_0_5 initval 0x38861C6361725B68312D4C07455611C59172460E5EC2730B06F445A0C6C3581B
    // exemplar attribute triglut_1_0_4 initval 0xC55187DD25E23B6456F3472C3802C0B3CD5AE6716C2E20D82E2A0181BBBD1429
    // exemplar attribute triglut_1_0_3 initval 0x554E80858B8530F882BF3B332C1B145B25B236B19363F16BFCECABD3AAA4E345
    // exemplar attribute triglut_1_0_2 initval 0x6842B2D288B3A5C340FE091D5E27A1DE85E886140D295FCFB1BD99F1D543FEE1
    // exemplar attribute triglut_1_0_1 initval 0x3881724E320AE0B6BAAFF5ACC0605C6BA883601860F00A55F60C643BC1D9B49B
    // exemplar attribute triglut_1_0_0 initval 0x7DA9764A29121F2372346A791C5D33DC7720D31BBDB67039B24F64B766013089
    // exemplar end

endmodule
