/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.5 */
/* Mon May 28 15:52:55 2012 */

/* parameterized module instance */
lattice_ram_24bit_16word __ (.WrAddress( ), .Data( ), .WrClock( ), 
    .WE( ), .WrClockEn( ), .RdAddress( ), .RdClock( ), .RdClockEn( ), 
    .Reset( ), .Q( ));
