/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* /usr/local/diamond/1.2/ispfpga/bin/lin/scuba -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type bram -wp 10 -rp 0011 -rdata_width 64 -data_width 16 -num_rows 2048 -outdata REGISTERED -resetmode SYNC -cascade -1 -e  */
/* Fri Sep 16 14:48:50 2011 */


`timescale 1 ns / 1 ps
module lattice_ram_16bit_4kbyte (WrAddress, RdAddress, Data, WE, RdClock, 
    RdClockEn, Reset, WrClock, WrClockEn, Q);
    input wire [10:0] WrAddress;
    input wire [8:0] RdAddress;
    input wire [15:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [63:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    // synopsys translate_off
    defparam lattice_ram_16bit_4kbyte_0_0_1.CSDECODE_B =  3'b000 ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.CSDECODE_A =  3'b000 ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.WRITEMODE_B = "NORMAL" ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.WRITEMODE_A = "NORMAL" ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.GSR = "DISABLED" ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.RESETMODE = "SYNC" ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.REGMODE_B = "OUTREG" ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.REGMODE_A = "OUTREG" ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.DATA_WIDTH_B = 36 ;
    defparam lattice_ram_16bit_4kbyte_0_0_1.DATA_WIDTH_A = 9 ;
    // synopsys translate_on
    DP16KB lattice_ram_16bit_4kbyte_0_0_1 (.DIA0(Data[0]), .DIA1(Data[1]), 
        .DIA2(Data[2]), .DIA3(Data[3]), .DIA4(Data[4]), .DIA5(Data[5]), 
        .DIA6(Data[6]), .DIA7(Data[7]), .DIA8(Data[8]), .DIA9(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), 
        .ADA0(scuba_vlo), .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), 
        .ADA4(WrAddress[1]), .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), 
        .ADA8(WrAddress[5]), .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), 
        .ADA11(WrAddress[8]), .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), 
        .CEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), 
        .ADB4(scuba_vlo), .ADB5(RdAddress[0]), .ADB6(RdAddress[1]), .ADB7(RdAddress[2]), 
        .ADB8(RdAddress[3]), .ADB9(RdAddress[4]), .ADB10(RdAddress[5]), 
        .ADB11(RdAddress[6]), .ADB12(RdAddress[7]), .ADB13(RdAddress[8]), 
        .CEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), .CSB0(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(Q[0]), .DOA1(Q[1]), 
        .DOA2(Q[2]), .DOA3(Q[3]), .DOA4(Q[4]), .DOA5(Q[5]), .DOA6(Q[6]), 
        .DOA7(Q[7]), .DOA8(Q[8]), .DOA9(Q[16]), .DOA10(Q[17]), .DOA11(Q[18]), 
        .DOA12(Q[19]), .DOA13(Q[20]), .DOA14(Q[21]), .DOA15(Q[22]), .DOA16(Q[23]), 
        .DOA17(Q[24]), .DOB0(Q[32]), .DOB1(Q[33]), .DOB2(Q[34]), .DOB3(Q[35]), 
        .DOB4(Q[36]), .DOB5(Q[37]), .DOB6(Q[38]), .DOB7(Q[39]), .DOB8(Q[40]), 
        .DOB9(Q[48]), .DOB10(Q[49]), .DOB11(Q[50]), .DOB12(Q[51]), .DOB13(Q[52]), 
        .DOB14(Q[53]), .DOB15(Q[54]), .DOB16(Q[55]), .DOB17(Q[56]))
             /* synthesis MEM_LPC_FILE="lattice_ram_16bit_4kbyte.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="36" */
             /* synthesis DATA_WIDTH_A="9" */;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam lattice_ram_16bit_4kbyte_0_1_0.CSDECODE_B =  3'b000 ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.CSDECODE_A =  3'b000 ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.WRITEMODE_B = "NORMAL" ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.WRITEMODE_A = "NORMAL" ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.GSR = "DISABLED" ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.RESETMODE = "SYNC" ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.REGMODE_B = "OUTREG" ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.REGMODE_A = "OUTREG" ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.DATA_WIDTH_B = 36 ;
    defparam lattice_ram_16bit_4kbyte_0_1_0.DATA_WIDTH_A = 9 ;
    // synopsys translate_on
    DP16KB lattice_ram_16bit_4kbyte_0_1_0 (.DIA0(Data[9]), .DIA1(Data[10]), 
        .DIA2(Data[11]), .DIA3(Data[12]), .DIA4(Data[13]), .DIA5(Data[14]), 
        .DIA6(Data[15]), .DIA7(scuba_vlo), .DIA8(scuba_vlo), .DIA9(scuba_vlo), 
        .DIA10(scuba_vlo), .DIA11(scuba_vlo), .DIA12(scuba_vlo), .DIA13(scuba_vlo), 
        .DIA14(scuba_vlo), .DIA15(scuba_vlo), .DIA16(scuba_vlo), .DIA17(scuba_vlo), 
        .ADA0(scuba_vlo), .ADA1(scuba_vlo), .ADA2(scuba_vlo), .ADA3(WrAddress[0]), 
        .ADA4(WrAddress[1]), .ADA5(WrAddress[2]), .ADA6(WrAddress[3]), .ADA7(WrAddress[4]), 
        .ADA8(WrAddress[5]), .ADA9(WrAddress[6]), .ADA10(WrAddress[7]), 
        .ADA11(WrAddress[8]), .ADA12(WrAddress[9]), .ADA13(WrAddress[10]), 
        .CEA(WrClockEn), .CLKA(WrClock), .WEA(WE), .CSA0(scuba_vlo), .CSA1(scuba_vlo), 
        .CSA2(scuba_vlo), .RSTA(Reset), .DIB0(scuba_vlo), .DIB1(scuba_vlo), 
        .DIB2(scuba_vlo), .DIB3(scuba_vlo), .DIB4(scuba_vlo), .DIB5(scuba_vlo), 
        .DIB6(scuba_vlo), .DIB7(scuba_vlo), .DIB8(scuba_vlo), .DIB9(scuba_vlo), 
        .DIB10(scuba_vlo), .DIB11(scuba_vlo), .DIB12(scuba_vlo), .DIB13(scuba_vlo), 
        .DIB14(scuba_vlo), .DIB15(scuba_vlo), .DIB16(scuba_vlo), .DIB17(scuba_vlo), 
        .ADB0(scuba_vlo), .ADB1(scuba_vlo), .ADB2(scuba_vlo), .ADB3(scuba_vlo), 
        .ADB4(scuba_vlo), .ADB5(RdAddress[0]), .ADB6(RdAddress[1]), .ADB7(RdAddress[2]), 
        .ADB8(RdAddress[3]), .ADB9(RdAddress[4]), .ADB10(RdAddress[5]), 
        .ADB11(RdAddress[6]), .ADB12(RdAddress[7]), .ADB13(RdAddress[8]), 
        .CEB(RdClockEn), .CLKB(RdClock), .WEB(scuba_vlo), .CSB0(scuba_vlo), 
        .CSB1(scuba_vlo), .CSB2(scuba_vlo), .RSTB(Reset), .DOA0(Q[9]), .DOA1(Q[10]), 
        .DOA2(Q[11]), .DOA3(Q[12]), .DOA4(Q[13]), .DOA5(Q[14]), .DOA6(Q[15]), 
        .DOA7(), .DOA8(), .DOA9(Q[25]), .DOA10(Q[26]), .DOA11(Q[27]), .DOA12(Q[28]), 
        .DOA13(Q[29]), .DOA14(Q[30]), .DOA15(Q[31]), .DOA16(), .DOA17(), 
        .DOB0(Q[41]), .DOB1(Q[42]), .DOB2(Q[43]), .DOB3(Q[44]), .DOB4(Q[45]), 
        .DOB5(Q[46]), .DOB6(Q[47]), .DOB7(), .DOB8(), .DOB9(Q[57]), .DOB10(Q[58]), 
        .DOB11(Q[59]), .DOB12(Q[60]), .DOB13(Q[61]), .DOB14(Q[62]), .DOB15(Q[63]), 
        .DOB16(), .DOB17())
             /* synthesis MEM_LPC_FILE="lattice_ram_16bit_4kbyte.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_B="0b000" */
             /* synthesis CSDECODE_A="0b000" */
             /* synthesis WRITEMODE_B="NORMAL" */
             /* synthesis WRITEMODE_A="NORMAL" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE_B="OUTREG" */
             /* synthesis REGMODE_A="OUTREG" */
             /* synthesis DATA_WIDTH_B="36" */
             /* synthesis DATA_WIDTH_A="9" */;



    // exemplar begin
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 MEM_LPC_FILE lattice_ram_16bit_4kbyte.lpc
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 MEM_INIT_FILE 
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 CSDECODE_B 0b000
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 CSDECODE_A 0b000
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 WRITEMODE_B NORMAL
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 WRITEMODE_A NORMAL
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 GSR DISABLED
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 RESETMODE SYNC
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 REGMODE_B OUTREG
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 REGMODE_A OUTREG
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 DATA_WIDTH_B 36
    // exemplar attribute lattice_ram_16bit_4kbyte_0_0_1 DATA_WIDTH_A 9
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 MEM_LPC_FILE lattice_ram_16bit_4kbyte.lpc
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 MEM_INIT_FILE 
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 CSDECODE_B 0b000
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 CSDECODE_A 0b000
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 WRITEMODE_B NORMAL
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 WRITEMODE_A NORMAL
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 GSR DISABLED
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 RESETMODE SYNC
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 REGMODE_B OUTREG
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 REGMODE_A OUTREG
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 DATA_WIDTH_B 36
    // exemplar attribute lattice_ram_16bit_4kbyte_0_1_0 DATA_WIDTH_A 9
    // exemplar end

endmodule
