/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 1.2 */
/* Fri Jun  1 13:42:36 2012 */

/* parameterized module instance */
lattice_sin_cos_table __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), 
    .Sine( ));
