/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* Fri Sep 16 14:48:50 2011 */

/* parameterized module instance */
lattice_ram_16bit_4kbyte __ (.WrAddress( ), .RdAddress( ), .Data( ), 
    .WE( ), .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), 
    .WrClockEn( ), .Q( ));
