/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.5 */
/* Thu Jun  7 09:59:39 2012 */

/* parameterized module instance */
lattice_ram_32bit_16 __ (.WrAddress( ), .Data( ), .WrClock( ), .WE( ), 
    .WrClockEn( ), .RdAddress( ), .RdClock( ), .RdClockEn( ), .Reset( ), 
    .Q( ));
