/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* Tue May 15 22:45:13 2012 */

/* parameterized module instance */
lattice_ram_72bit_512 __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
