/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.5 */
/* Tue May  8 11:45:30 2012 */

/* parameterized module instance */
lattice_ram_24bit_16word __ (.WrAddress( ), .Data( ), .WrClock( ), 
    .WE( ), .WrClockEn( ), .RdAddress( ), .Q( ));
