/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* Thu Sep  8 13:53:19 2011 */

/* parameterized module instance */
lattice_ram_16bit __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
