/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.5 */
/* Tue Jun  5 23:00:55 2012 */

/* parameterized module instance */
lattice_ram_36bit_16 __ (.WrAddress( ), .Data( ), .WrClock( ), .WE( ), 
    .WrClockEn( ), .RdAddress( ), .RdClock( ), .RdClockEn( ), .Reset( ), 
    .Q( ));
