/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* /usr/local/diamond/1.2/ispfpga/bin/lin/scuba -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type bram -wp 10 -rp 0011 -rdata_width 72 -data_width 72 -num_rows 512 -outdata REGISTERED -resetmode SYNC -cascade -1 -e  */
/* Tue May 15 22:45:13 2012 */


`timescale 1 ns / 1 ps
module lattice_ram_72bit_512 (WrAddress, RdAddress, Data, WE, RdClock, 
    RdClockEn, Reset, WrClock, WrClockEn, Q);
    input wire [8:0] WrAddress;
    input wire [8:0] RdAddress;
    input wire [71:0] Data;
    input wire WE;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    input wire WrClock;
    input wire WrClockEn;
    output wire [71:0] Q;

    wire scuba_vhi;
    wire scuba_vlo;

    // synopsys translate_off
    defparam lattice_ram_72bit_512_0_0_1.CSDECODE_R =  3'b000 ;
    defparam lattice_ram_72bit_512_0_0_1.CSDECODE_W =  3'b001 ;
    defparam lattice_ram_72bit_512_0_0_1.GSR = "DISABLED" ;
    defparam lattice_ram_72bit_512_0_0_1.RESETMODE = "SYNC" ;
    defparam lattice_ram_72bit_512_0_0_1.REGMODE = "OUTREG" ;
    defparam lattice_ram_72bit_512_0_0_1.DATA_WIDTH_R = 36 ;
    defparam lattice_ram_72bit_512_0_0_1.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB lattice_ram_72bit_512_0_0_1 (.DI0(Data[0]), .DI1(Data[1]), 
        .DI2(Data[2]), .DI3(Data[3]), .DI4(Data[4]), .DI5(Data[5]), .DI6(Data[6]), 
        .DI7(Data[7]), .DI8(Data[8]), .DI9(Data[9]), .DI10(Data[10]), .DI11(Data[11]), 
        .DI12(Data[12]), .DI13(Data[13]), .DI14(Data[14]), .DI15(Data[15]), 
        .DI16(Data[16]), .DI17(Data[17]), .DI18(Data[18]), .DI19(Data[19]), 
        .DI20(Data[20]), .DI21(Data[21]), .DI22(Data[22]), .DI23(Data[23]), 
        .DI24(Data[24]), .DI25(Data[25]), .DI26(Data[26]), .DI27(Data[27]), 
        .DI28(Data[28]), .DI29(Data[29]), .DI30(Data[30]), .DI31(Data[31]), 
        .DI32(Data[32]), .DI33(Data[33]), .DI34(Data[34]), .DI35(Data[35]), 
        .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), .ADW2(WrAddress[2]), .ADW3(WrAddress[3]), 
        .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), .ADW6(WrAddress[6]), .ADW7(WrAddress[7]), 
        .ADW8(WrAddress[8]), .BE0(scuba_vhi), .BE1(scuba_vhi), .BE2(scuba_vhi), 
        .BE3(scuba_vhi), .CEW(WrClockEn), .CLKW(WrClock), .CSW0(WE), .CSW1(scuba_vlo), 
        .CSW2(scuba_vlo), .ADR0(scuba_vlo), .ADR1(scuba_vlo), .ADR2(scuba_vlo), 
        .ADR3(scuba_vlo), .ADR4(scuba_vlo), .ADR5(RdAddress[0]), .ADR6(RdAddress[1]), 
        .ADR7(RdAddress[2]), .ADR8(RdAddress[3]), .ADR9(RdAddress[4]), .ADR10(RdAddress[5]), 
        .ADR11(RdAddress[6]), .ADR12(RdAddress[7]), .ADR13(RdAddress[8]), 
        .CER(RdClockEn), .CLKR(RdClock), .CSR0(scuba_vlo), .CSR1(scuba_vlo), 
        .CSR2(scuba_vlo), .RST(Reset), .DO0(Q[18]), .DO1(Q[19]), .DO2(Q[20]), 
        .DO3(Q[21]), .DO4(Q[22]), .DO5(Q[23]), .DO6(Q[24]), .DO7(Q[25]), 
        .DO8(Q[26]), .DO9(Q[27]), .DO10(Q[28]), .DO11(Q[29]), .DO12(Q[30]), 
        .DO13(Q[31]), .DO14(Q[32]), .DO15(Q[33]), .DO16(Q[34]), .DO17(Q[35]), 
        .DO18(Q[0]), .DO19(Q[1]), .DO20(Q[2]), .DO21(Q[3]), .DO22(Q[4]), 
        .DO23(Q[5]), .DO24(Q[6]), .DO25(Q[7]), .DO26(Q[8]), .DO27(Q[9]), 
        .DO28(Q[10]), .DO29(Q[11]), .DO30(Q[12]), .DO31(Q[13]), .DO32(Q[14]), 
        .DO33(Q[15]), .DO34(Q[16]), .DO35(Q[17]))
             /* synthesis MEM_LPC_FILE="lattice_ram_72bit_512.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="OUTREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    // synopsys translate_off
    defparam lattice_ram_72bit_512_0_1_0.CSDECODE_R =  3'b000 ;
    defparam lattice_ram_72bit_512_0_1_0.CSDECODE_W =  3'b001 ;
    defparam lattice_ram_72bit_512_0_1_0.GSR = "DISABLED" ;
    defparam lattice_ram_72bit_512_0_1_0.RESETMODE = "SYNC" ;
    defparam lattice_ram_72bit_512_0_1_0.REGMODE = "OUTREG" ;
    defparam lattice_ram_72bit_512_0_1_0.DATA_WIDTH_R = 36 ;
    defparam lattice_ram_72bit_512_0_1_0.DATA_WIDTH_W = 36 ;
    // synopsys translate_on
    PDPW16KB lattice_ram_72bit_512_0_1_0 (.DI0(Data[36]), .DI1(Data[37]), 
        .DI2(Data[38]), .DI3(Data[39]), .DI4(Data[40]), .DI5(Data[41]), 
        .DI6(Data[42]), .DI7(Data[43]), .DI8(Data[44]), .DI9(Data[45]), 
        .DI10(Data[46]), .DI11(Data[47]), .DI12(Data[48]), .DI13(Data[49]), 
        .DI14(Data[50]), .DI15(Data[51]), .DI16(Data[52]), .DI17(Data[53]), 
        .DI18(Data[54]), .DI19(Data[55]), .DI20(Data[56]), .DI21(Data[57]), 
        .DI22(Data[58]), .DI23(Data[59]), .DI24(Data[60]), .DI25(Data[61]), 
        .DI26(Data[62]), .DI27(Data[63]), .DI28(Data[64]), .DI29(Data[65]), 
        .DI30(Data[66]), .DI31(Data[67]), .DI32(Data[68]), .DI33(Data[69]), 
        .DI34(Data[70]), .DI35(Data[71]), .ADW0(WrAddress[0]), .ADW1(WrAddress[1]), 
        .ADW2(WrAddress[2]), .ADW3(WrAddress[3]), .ADW4(WrAddress[4]), .ADW5(WrAddress[5]), 
        .ADW6(WrAddress[6]), .ADW7(WrAddress[7]), .ADW8(WrAddress[8]), .BE0(scuba_vhi), 
        .BE1(scuba_vhi), .BE2(scuba_vhi), .BE3(scuba_vhi), .CEW(WrClockEn), 
        .CLKW(WrClock), .CSW0(WE), .CSW1(scuba_vlo), .CSW2(scuba_vlo), .ADR0(scuba_vlo), 
        .ADR1(scuba_vlo), .ADR2(scuba_vlo), .ADR3(scuba_vlo), .ADR4(scuba_vlo), 
        .ADR5(RdAddress[0]), .ADR6(RdAddress[1]), .ADR7(RdAddress[2]), .ADR8(RdAddress[3]), 
        .ADR9(RdAddress[4]), .ADR10(RdAddress[5]), .ADR11(RdAddress[6]), 
        .ADR12(RdAddress[7]), .ADR13(RdAddress[8]), .CER(RdClockEn), .CLKR(RdClock), 
        .CSR0(scuba_vlo), .CSR1(scuba_vlo), .CSR2(scuba_vlo), .RST(Reset), 
        .DO0(Q[54]), .DO1(Q[55]), .DO2(Q[56]), .DO3(Q[57]), .DO4(Q[58]), 
        .DO5(Q[59]), .DO6(Q[60]), .DO7(Q[61]), .DO8(Q[62]), .DO9(Q[63]), 
        .DO10(Q[64]), .DO11(Q[65]), .DO12(Q[66]), .DO13(Q[67]), .DO14(Q[68]), 
        .DO15(Q[69]), .DO16(Q[70]), .DO17(Q[71]), .DO18(Q[36]), .DO19(Q[37]), 
        .DO20(Q[38]), .DO21(Q[39]), .DO22(Q[40]), .DO23(Q[41]), .DO24(Q[42]), 
        .DO25(Q[43]), .DO26(Q[44]), .DO27(Q[45]), .DO28(Q[46]), .DO29(Q[47]), 
        .DO30(Q[48]), .DO31(Q[49]), .DO32(Q[50]), .DO33(Q[51]), .DO34(Q[52]), 
        .DO35(Q[53]))
             /* synthesis MEM_LPC_FILE="lattice_ram_72bit_512.lpc" */
             /* synthesis MEM_INIT_FILE="" */
             /* synthesis CSDECODE_R="0b000" */
             /* synthesis CSDECODE_W="0b001" */
             /* synthesis GSR="DISABLED" */
             /* synthesis RESETMODE="SYNC" */
             /* synthesis REGMODE="OUTREG" */
             /* synthesis DATA_WIDTH_R="36" */
             /* synthesis DATA_WIDTH_W="36" */;



    // exemplar begin
    // exemplar attribute lattice_ram_72bit_512_0_0_1 MEM_LPC_FILE lattice_ram_72bit_512.lpc
    // exemplar attribute lattice_ram_72bit_512_0_0_1 MEM_INIT_FILE 
    // exemplar attribute lattice_ram_72bit_512_0_0_1 CSDECODE_R 0b000
    // exemplar attribute lattice_ram_72bit_512_0_0_1 CSDECODE_W 0b001
    // exemplar attribute lattice_ram_72bit_512_0_0_1 GSR DISABLED
    // exemplar attribute lattice_ram_72bit_512_0_0_1 RESETMODE SYNC
    // exemplar attribute lattice_ram_72bit_512_0_0_1 REGMODE OUTREG
    // exemplar attribute lattice_ram_72bit_512_0_0_1 DATA_WIDTH_R 36
    // exemplar attribute lattice_ram_72bit_512_0_0_1 DATA_WIDTH_W 36
    // exemplar attribute lattice_ram_72bit_512_0_1_0 MEM_LPC_FILE lattice_ram_72bit_512.lpc
    // exemplar attribute lattice_ram_72bit_512_0_1_0 MEM_INIT_FILE 
    // exemplar attribute lattice_ram_72bit_512_0_1_0 CSDECODE_R 0b000
    // exemplar attribute lattice_ram_72bit_512_0_1_0 CSDECODE_W 0b001
    // exemplar attribute lattice_ram_72bit_512_0_1_0 GSR DISABLED
    // exemplar attribute lattice_ram_72bit_512_0_1_0 RESETMODE SYNC
    // exemplar attribute lattice_ram_72bit_512_0_1_0 REGMODE OUTREG
    // exemplar attribute lattice_ram_72bit_512_0_1_0 DATA_WIDTH_R 36
    // exemplar attribute lattice_ram_72bit_512_0_1_0 DATA_WIDTH_W 36
    // exemplar end

endmodule
