/* Verilog module instantiation template generated by SCUBA Diamond_1.1_Production (517) */
/* Module Version: 6.1 */
/* Thu Dec 23 15:34:18 2010 */

/* parameterized module instance */
lattice_ram __ (.WrAddress( ), .RdAddress( ), .Data( ), .WE( ), 
    .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), .WrClockEn( ), 
    .Q( ));
