/* Verilog netlist generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 3.5 */
/* /usr/local/diamond/1.2/ispfpga/bin/lin/scuba -w -lang verilog -synth synplify -bus_exp 7 -bb -arch mg5a00 -type sdpram -rdata_width 36 -data_width 36 -num_rows 16 -outData REGISTERED -e  */
/* Tue Jun  5 23:00:55 2012 */


`timescale 1 ns / 1 ps
module lattice_ram_36bit_16 (WrAddress, Data, WrClock, WE, WrClockEn, 
    RdAddress, RdClock, RdClockEn, Reset, Q);
    input wire [3:0] WrAddress;
    input wire [35:0] Data;
    input wire WrClock;
    input wire WE;
    input wire WrClockEn;
    input wire [3:0] RdAddress;
    input wire RdClock;
    input wire RdClockEn;
    input wire Reset;
    output wire [35:0] Q;

    wire scuba_vlo;
    wire scuba_vhi;
    wire dataout35_ffin;
    wire dataout34_ffin;
    wire dataout33_ffin;
    wire dataout32_ffin;
    wire dataout31_ffin;
    wire dataout30_ffin;
    wire dataout29_ffin;
    wire dataout28_ffin;
    wire dataout27_ffin;
    wire dataout26_ffin;
    wire dataout25_ffin;
    wire dataout24_ffin;
    wire dataout23_ffin;
    wire dataout22_ffin;
    wire dataout21_ffin;
    wire dataout20_ffin;
    wire dataout19_ffin;
    wire dataout18_ffin;
    wire dataout17_ffin;
    wire dataout16_ffin;
    wire dataout15_ffin;
    wire dataout14_ffin;
    wire dataout13_ffin;
    wire dataout12_ffin;
    wire dataout11_ffin;
    wire dataout10_ffin;
    wire dataout9_ffin;
    wire dataout8_ffin;
    wire dataout7_ffin;
    wire dataout6_ffin;
    wire dataout5_ffin;
    wire dataout4_ffin;
    wire dataout3_ffin;
    wire dataout2_ffin;
    wire dataout1_ffin;
    wire dataout0_ffin;
    wire dec0_wre3;

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    // synopsys translate_off
    defparam LUT4_0.initval =  16'h8000 ;
    // synopsys translate_on
    ROM16X1 LUT4_0 (.AD3(WE), .AD2(WrClockEn), .AD1(scuba_vhi), .AD0(scuba_vhi), 
        .DO0(dec0_wre3))
             /* synthesis initval="0x8000" */;

    // synopsys translate_off
    defparam FF_35.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_35 (.D(dataout35_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[35]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_34.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_34 (.D(dataout34_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[34]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_33.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_33 (.D(dataout33_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[33]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_32.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_32 (.D(dataout32_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[32]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_31.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_31 (.D(dataout31_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[31]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_30.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_30 (.D(dataout30_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[30]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_29.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_29 (.D(dataout29_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[29]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_28.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_28 (.D(dataout28_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[28]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_27.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_27 (.D(dataout27_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[27]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_26.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_26 (.D(dataout26_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[26]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_25.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_25 (.D(dataout25_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[25]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_24.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_24 (.D(dataout24_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[24]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_23.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_23 (.D(dataout23_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[23]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_22.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_22 (.D(dataout22_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[22]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_21.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_21 (.D(dataout21_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[21]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_20.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_20 (.D(dataout20_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[20]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_19.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_19 (.D(dataout19_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[19]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_18.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_18 (.D(dataout18_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[18]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_17.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_17 (.D(dataout17_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[17]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_16.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_16 (.D(dataout16_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[16]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_15.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_15 (.D(dataout15_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[15]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_14.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_14 (.D(dataout14_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[14]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_13.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_13 (.D(dataout13_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[13]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_12.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_12 (.D(dataout12_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[12]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_11.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_11 (.D(dataout11_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[11]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_10.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_10 (.D(dataout10_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[10]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_9.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_9 (.D(dataout9_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[9]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_8.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_8 (.D(dataout8_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[8]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_7.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_7 (.D(dataout7_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[7]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_6.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_6 (.D(dataout6_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[6]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_5.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_5 (.D(dataout5_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[5]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_4.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_4 (.D(dataout4_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[4]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_3.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_3 (.D(dataout3_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[3]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_2.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_2 (.D(dataout2_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[2]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_1.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_1 (.D(dataout1_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[1]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam FF_0.GSR = "ENABLED" ;
    // synopsys translate_on
    FD1P3DX FF_0 (.D(dataout0_ffin), .SP(RdClockEn), .CK(RdClock), .CD(Reset), 
        .Q(Q[0]))
             /* synthesis GSR="ENABLED" */;

    // synopsys translate_off
    defparam mem_0_0.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_0 (.DI0(Data[32]), .DI1(Data[33]), .DI2(Data[34]), .DI3(Data[35]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout32_ffin), 
        .DO1(dataout33_ffin), .DO2(dataout34_ffin), .DO3(dataout35_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(0-3)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_0" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_1.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_1 (.DI0(Data[28]), .DI1(Data[29]), .DI2(Data[30]), .DI3(Data[31]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout28_ffin), 
        .DO1(dataout29_ffin), .DO2(dataout30_ffin), .DO3(dataout31_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(4-7)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_1" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_2.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_2 (.DI0(Data[24]), .DI1(Data[25]), .DI2(Data[26]), .DI3(Data[27]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout24_ffin), 
        .DO1(dataout25_ffin), .DO2(dataout26_ffin), .DO3(dataout27_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(8-11)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_2" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_3.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_3 (.DI0(Data[20]), .DI1(Data[21]), .DI2(Data[22]), .DI3(Data[23]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout20_ffin), 
        .DO1(dataout21_ffin), .DO2(dataout22_ffin), .DO3(dataout23_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(12-15)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_3" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_4.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_4 (.DI0(Data[16]), .DI1(Data[17]), .DI2(Data[18]), .DI3(Data[19]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout16_ffin), 
        .DO1(dataout17_ffin), .DO2(dataout18_ffin), .DO3(dataout19_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(16-19)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_4" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_5.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_5 (.DI0(Data[12]), .DI1(Data[13]), .DI2(Data[14]), .DI3(Data[15]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout12_ffin), 
        .DO1(dataout13_ffin), .DO2(dataout14_ffin), .DO3(dataout15_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(20-23)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_5" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_6.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_6 (.DI0(Data[8]), .DI1(Data[9]), .DI2(Data[10]), .DI3(Data[11]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout8_ffin), .DO1(dataout9_ffin), 
        .DO2(dataout10_ffin), .DO3(dataout11_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(24-27)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_6" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_7.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_7 (.DI0(Data[4]), .DI1(Data[5]), .DI2(Data[6]), .DI3(Data[7]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout4_ffin), .DO1(dataout5_ffin), 
        .DO2(dataout6_ffin), .DO3(dataout7_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(28-31)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_7" */
             /* synthesis initval="0x0000000000000000" */;

    // synopsys translate_off
    defparam mem_0_8.initval =  64'h0000000000000000 ;
    // synopsys translate_on
    DPR16X4B mem_0_8 (.DI0(Data[0]), .DI1(Data[1]), .DI2(Data[2]), .DI3(Data[3]), 
        .WCK(WrClock), .WRE(dec0_wre3), .RAD0(RdAddress[0]), .RAD1(RdAddress[1]), 
        .RAD2(RdAddress[2]), .RAD3(RdAddress[3]), .WAD0(WrAddress[0]), .WAD1(WrAddress[1]), 
        .WAD2(WrAddress[2]), .WAD3(WrAddress[3]), .DO0(dataout0_ffin), .DO1(dataout1_ffin), 
        .DO2(dataout2_ffin), .DO3(dataout3_ffin))
             /* synthesis MEM_INIT_FILE="(0-15)(32-35)" */
             /* synthesis MEM_LPC_FILE="lattice_ram_36bit_16.lpc" */
             /* synthesis COMP="mem_0_8" */
             /* synthesis initval="0x0000000000000000" */;



    // exemplar begin
    // exemplar attribute LUT4_0 initval 0x8000
    // exemplar attribute FF_35 GSR ENABLED
    // exemplar attribute FF_34 GSR ENABLED
    // exemplar attribute FF_33 GSR ENABLED
    // exemplar attribute FF_32 GSR ENABLED
    // exemplar attribute FF_31 GSR ENABLED
    // exemplar attribute FF_30 GSR ENABLED
    // exemplar attribute FF_29 GSR ENABLED
    // exemplar attribute FF_28 GSR ENABLED
    // exemplar attribute FF_27 GSR ENABLED
    // exemplar attribute FF_26 GSR ENABLED
    // exemplar attribute FF_25 GSR ENABLED
    // exemplar attribute FF_24 GSR ENABLED
    // exemplar attribute FF_23 GSR ENABLED
    // exemplar attribute FF_22 GSR ENABLED
    // exemplar attribute FF_21 GSR ENABLED
    // exemplar attribute FF_20 GSR ENABLED
    // exemplar attribute FF_19 GSR ENABLED
    // exemplar attribute FF_18 GSR ENABLED
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar attribute mem_0_0 MEM_INIT_FILE (0-15)(0-3)
    // exemplar attribute mem_0_0 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_0 COMP mem_0_0
    // exemplar attribute mem_0_0 initval 0x0000000000000000
    // exemplar attribute mem_0_1 MEM_INIT_FILE (0-15)(4-7)
    // exemplar attribute mem_0_1 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_1 COMP mem_0_1
    // exemplar attribute mem_0_1 initval 0x0000000000000000
    // exemplar attribute mem_0_2 MEM_INIT_FILE (0-15)(8-11)
    // exemplar attribute mem_0_2 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_2 COMP mem_0_2
    // exemplar attribute mem_0_2 initval 0x0000000000000000
    // exemplar attribute mem_0_3 MEM_INIT_FILE (0-15)(12-15)
    // exemplar attribute mem_0_3 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_3 COMP mem_0_3
    // exemplar attribute mem_0_3 initval 0x0000000000000000
    // exemplar attribute mem_0_4 MEM_INIT_FILE (0-15)(16-19)
    // exemplar attribute mem_0_4 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_4 COMP mem_0_4
    // exemplar attribute mem_0_4 initval 0x0000000000000000
    // exemplar attribute mem_0_5 MEM_INIT_FILE (0-15)(20-23)
    // exemplar attribute mem_0_5 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_5 COMP mem_0_5
    // exemplar attribute mem_0_5 initval 0x0000000000000000
    // exemplar attribute mem_0_6 MEM_INIT_FILE (0-15)(24-27)
    // exemplar attribute mem_0_6 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_6 COMP mem_0_6
    // exemplar attribute mem_0_6 initval 0x0000000000000000
    // exemplar attribute mem_0_7 MEM_INIT_FILE (0-15)(28-31)
    // exemplar attribute mem_0_7 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_7 COMP mem_0_7
    // exemplar attribute mem_0_7 initval 0x0000000000000000
    // exemplar attribute mem_0_8 MEM_INIT_FILE (0-15)(32-35)
    // exemplar attribute mem_0_8 MEM_LPC_FILE lattice_ram_36bit_16.lpc
    // exemplar attribute mem_0_8 COMP mem_0_8
    // exemplar attribute mem_0_8 initval 0x0000000000000000
    // exemplar end

endmodule
