/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 6.1 */
/* Wed Sep 14 13:52:00 2011 */

/* parameterized module instance */
lattice_ram_16bit_8kbyte __ (.WrAddress( ), .RdAddress( ), .Data( ), 
    .WE( ), .RdClock( ), .RdClockEn( ), .Reset( ), .WrClock( ), 
    .WrClockEn( ), .Q( ));
