/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 5.2 */
/* Mon Sep 26 16:31:23 2011 */

/* parameterized module instance */
pll2 __ (.CLK( ), .CLKOP( ), .LOCK( ));
