/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 5.2 */
/* Mon Apr 16 17:56:26 2012 */

/* parameterized module instance */
pll2 __ (.CLK( ), .CLKOP( ), .CLKOK( ), .LOCK( ));
