/* Verilog module instantiation template generated by SCUBA Diamond_1.2_Production (92) */
/* Module Version: 5.2 */
/* Mon Sep 26 11:39:03 2011 */

/* parameterized module instance */
pll __ (.CLK( ), .WRDEL( ), .DPHASE0( ), .DPHASE1( ), .DPHASE2( ), 
    .DPHASE3( ), .CLKOP( ), .CLKOS( ), .CLKOK( ), .LOCK( ));
