/* Verilog module instantiation template generated by SCUBA Diamond_1.1_Production (517) */
/* Module Version: 5.2 */
/* Thu Dec 23 15:34:31 2010 */

/* parameterized module instance */
pll __ (.CLK( ), .WRDEL( ), .DPHASE0( ), .DPHASE1( ), .DPHASE2( ), 
    .DPHASE3( ), .CLKOP( ), .CLKOS( ), .LOCK( ));
