/* Verilog module instantiation template generated by SCUBA Diamond_1.1_Production (517) */
/* Module Version: 5.2 */
/* Thu Dec 23 15:34:26 2010 */

/* parameterized module instance */
pll2 __ (.CLK( ), .CLKOP( ), .LOCK( ));
