/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Real-Time Workshop, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Real-Time Workshop User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Thu Jan 28 19:27:05 2010
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void SDFPAdder4_Outputs_wrapper(const uint32_T *in0,
                          const uint32_T *in1,
                          const uint32_T *in2,
                          const uint32_T *in3,
                          uint32_T *adder_out  , 
                          const uint32_T  *in_bitwidth, const int_T  p_width0, 
                          const uint32_T  *in_fp_position, const int_T  p_width1, 
                          const uint32_T  *out_bitwidth, const int_T  p_width2, 
                          const uint32_T  *out_fp_position,  const int_T p_width3)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
         y0[0] = u0[0];
For complex signals use: y0[0].re = u0[0].re;
                         y0[0].im = u0[0].im;
                         y1[0].re = u1[0].re;
                         y1[0].im = u1[0].im;*/
 
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */


#define dprintf(format, args ...) ;

   /* Just "rename" the input parameters. */
   uint32_T t_in0 = in0[0];
   uint32_T t_in1 = in1[0];
   uint32_T t_in2 = in2[0];
   uint32_T t_in3 = in3[0];
   uint32_T t_in_bitwidth = in_bitwidth[0];
   uint32_T t_in_fp_position = in_fp_position[0];
   uint32_T t_out_bitwidth = out_bitwidth[0];
   uint32_T t_out_fp_position = out_fp_position[0];
   uint32_T t_adder_out;

   /* Do sum. */
   t_adder_out = t_in0 + t_in1 + t_in2 + t_in3;
   dprintf("t_adder_out = %08x\n", t_adder_out );

   /* Make any adjustments if necessary. */
   if( t_out_fp_position < t_in_fp_position ) {
      /* shift right */
      t_adder_out >>= (t_in_fp_position - t_out_fp_position);
      dprintf("shift t_adder_out by %d bits\n", (t_in_fp_position - t_out_fp_position));
   } else if( t_out_fp_position > t_in_fp_position ) {
      /* shift left if we don't have enough bits. */
      t_adder_out <<= (t_out_fp_position - t_in_fp_position);
   }
   dprintf("t_adder_out, adjusted = %08x\n", t_adder_out );
   
   /* Mask out bits to mimick truncation. */
   uint32_T mask;
   if( t_out_bitwidth < 32 ) 
      mask = (1 << t_out_bitwidth)-1;
   else
      mask = 0xFFFFFFFF;
   dprintf("mask = %08x\n", (1 << t_out_bitwidth) );
   t_adder_out &= mask;

   *adder_out = t_adder_out;

}
