/* Verilog module instantiation template generated by SCUBA Diamond_1.1_Production (517) */
/* Module Version: 2.0 */
/* Thu Dec 23 15:34:13 2010 */

/* parameterized module instance */
tagmem __ (.CLK( ), .SI( ), .CS( ), .SO( ));
